---
services:
  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch
    restart: always
    environment:
      TZ: Europe/Moscow
      node.name: opensearch
      discovery.type: single-node
      cluster.name: opensearch-cluster
      plugins.security.ssl.transport.pemkey_filepath: certs/opensearch/opensearch.key
      plugins.security.ssl.transport.pemcert_filepath: certs/opensearch/opensearch.pem
      plugins.security.ssl.http.pemkey_filepath: certs/opensearch/opensearch.key
      plugins.security.ssl.http.pemcert_filepath: certs/opensearch/opensearch.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      OPENSEARCH_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "./volumes/config/:/usr/share/opensearch/config/"
      - "./volumes/opensearch-data:/usr/share/opensearch/data"
      - "./volumes/certs/:/usr/share/opensearch/config/certs:ro"
      - "./volumes/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch_net

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    restart: always
    logging:
      options:
        max-size: "1000m"
        max-file: "2"
    ports:
      - 5601:5601
    volumes:
      - "./volumes/certs:/usr/share/opensearch-dashboards/config/certs:ro"
      - "./volumes/opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    environment:
      TZ: "Europe/Moscow"
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' 
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    networks:
      - opensearch_net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    container_name: logstash
    restart: always
    logging:
      options:
        max-size: "1000m"
        max-file: "3"
    ports:
      - "5044:5044"
    volumes:
      - ./volumes/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./volumes/logstash/conf.d/:/usr/share/logstash/config/conf.d/
      - ./volumes/logstash/certs/:/usr/share/logstash/config/certs/
    environment:
      - "TZ=Europe/Moscow"
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - opensearch_net
    depends_on:
      - opensearch

networks:
  opensearch_net:
    driver: bridge